from . import back
from . import start
from . import settings
from . import settings_change_language
from . import settings_change_phone_number
from . import categories
from . import about_me
from . import lessons
from . import lesson
from . import grant_access
from . import close_access
from . import send_homework
from . import video_id
from . import accept_or_deny_homework
